### ISSUE TITLE
Homework Week 2

### ISSUE THREAD

**Issue by kevinmccartney** [mleo2857/js-app-dev-week-2#1]
Hey Mike!

Looked over the homework for week 2 & had a few callouts.

1. In `gratuity.js` make sure that you're assigning your variables with a keyword. Otherwise, they're all in the global scope.
2. in `rockPaperScissors.js`, in your `playGame` function, make sure that you're returning the winning player object.

**Comment by mleo2857** [comment]
Updated issues

**Comment by kevinmccartney** [comment]
Nicely done! :+1:
